const express = require("express");
const { savePaper, getPaperById } = require("../controllers/paperController");
const { isVerifiedUser } = require("../middlewares/tokenVerification");
const router = express.Router();

// Save paper generated by AI (POST /api/papers)
router.route("/").post(isVerifiedUser, savePaper);

// Get paper by id (GET /api/papers/:paperId)
router.route("/:paperId").get(isVerifiedUser, getPaperById);

module.exports = router;