const createHttpError = require("http-errors");
const Paper = require("../models/paperModel");
const User = require("../models/userModel");

// Save paper generated by AI
const savePaper = async (req, res, next) => {
  try {
    const userId = req.user._id;
    const {
      examType,
      subjects,
      topics,
      sets,
      numberOfQuestions,
      questions
    } = req.body;

    // Validate required fields
    if (!examType || !subjects || !topics || !numberOfQuestions || !questions) {
      const error = createHttpError(400, "All required fields must be provided");
      return next(error);
    }

    // Validate questions array
    if (!Array.isArray(questions) || questions.length === 0) {
      const error = createHttpError(400, "Questions array is required and must not be empty");
      return next(error);
    }

    // Create paper
    const newPaper = await Paper.create({
      examType,
      subjects,
      topics,
      sets: sets || 1,
      numberOfQuestions,
      questions,
      createdBy: userId
    });

    // Add paper to user's papers array
    const user = await User.findById(userId);
    if (!user) {
      const error = createHttpError(404, "User not found");
      return next(error);
    }

    user.papers.push(newPaper._id);
    await user.save();

    res.status(201).json({
      success: true,
      message: "Paper saved successfully",
      data: newPaper
    });
  } catch (error) {
    next(error);
  }
};

// Get paper by id
const getPaperById = async (req, res, next) => {
  try {
    const { paperId } = req.params;
    const userId = req.user._id;

    if (!paperId) {
      const error = createHttpError(400, "Paper ID is required");
      return next(error);
    }

    const paper = await Paper.findById(paperId).populate("createdBy", "email");

    if (!paper) {
      const error = createHttpError(404, "Paper not found");
      return next(error);
    }

    // Verify that the paper belongs to the authenticated user
    if (paper.createdBy._id.toString() !== userId.toString()) {
      const error = createHttpError(403, "You don't have permission to access this paper");
      return next(error);
    }

    res.status(200).json({
      success: true,
      message: "Paper fetched successfully",
      data: paper
    });
  } catch (error) {
    next(error);
  }
};

module.exports = { savePaper, getPaperById };